#!/bin/bash
while getopts p: flag
do 
    case "$flag" in
        p) port=${OPTARG};;
    esac
done

if [ -z "$port" ];
then
    read -p 'Which port should I check? ' port
    while [ -z "$port" ]
    do
        echo "[WARNING] I won't be able to proceed without a port";
        read -p "Which port should I check? " port
    done
fi

while ! [[ "$port" =~ ^[0-9]+$ ]]
do
    echo "port should be integer";
    read -p "Which port should I check? " port
done

echo Checking port $port...

processId=`lsof -i tcp:$port | grep LISTEN | tr -s ' ' | cut -d ' ' -f 2`

if [ ! -z "$processId" ];
then
    echo PID is $processId
    read -p "Do you want to kill this process? (yes/no) " yn
    case $yn in
        [yY] ) echo ok, killing process $processId
            kill -9 $processId
            echo process killed, have a good day
            exit;;

        [nN] ) echo exiting, have a good day
            exit 1;;
        * ) echo invalid response;;
    esac
else
    echo nothing on port $port
fi
